apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-deployment
  labels:
    app: aceest-fitness
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: aceest-fitness
  template:
    metadata:
      labels:
        app: aceest-fitness
    spec:
      containers:
      - name: aceest-flask-app
        image: sharanraj67/aceest-fitness:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
spec:
  type: LoadBalancer 
  selector:
    app: aceest-fitness
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000